# Botón "Sponsor" del repositorio. GitHub lo muestra automáticamente en la
# cabecera del repo una vez que tu perfil de GitHub Sponsors esté activado en
# https://github.com/sponsors
github: [GoNNoTDa]
